# Generated by Django 5.1 on 2024-08-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_administrator',
            field=models.BooleanField(default=False, verbose_name='Are you a SchoolAdministrator?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Are you a Student?'),
        ),
    ]
