# Generated by Django 5.1 on 2024-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='t_and_c',
            field=models.BooleanField(default=False),
        ),
    ]
