# Generated by Django 5.1 on 2024-08-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_transcriptrequest_doc_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptrequest',
            old_name='comment',
            new_name='purpose',
        ),
    ]
