# Generated by Django 5.1 on 2024-08-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_comment_transcriptrequest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorprofile',
            name='institution_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
