# Generated by Django 5.1 on 2024-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_administratorprofile_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_incomplete',
            field=models.BooleanField(default=True),
        ),
    ]
