# Generated by Django 5.1 on 2024-08-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_studentprofile_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.ForeignKey(default=0.1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.administratorprofile'),
            preserve_default=False,
        ),
    ]
