# Generated by Django 5.1 on 2024-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_studentprofile_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
