# Generated by Django 5.1 on 2024-08-25 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_studentprofile_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptrequest',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='transcriptrequest',
            name='student',
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('None', 'None'), ('Degree', 'Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('transcript', 'Transcript'), ('recommendation_letter', 'Recommendation Letter')], default='None', max_length=50)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sender_email', models.EmailField(max_length=254)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.administratorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='RecommendationLetterRequest',
        ),
        migrations.DeleteModel(
            name='TranscriptRequest',
        ),
    ]
