# Generated by Django 5.1 on 2024-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_transcriptrequest_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdocument',
            name='status',
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='is_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
