# Generated by Django 5.1 on 2024-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_requestdocument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
