# Generated by Django 5.1 on 2024-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_subscription_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
