# Generated by Django 5.1 on 2024-08-26 21:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_subscription_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveIntegerField()),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=255)),
                ('grade_10', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_11', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_12', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_10_average', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_11_average', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_12_average', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_10_conduct', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_11_conduct', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_12_conduct', models.CharField(blank=True, max_length=50, null=True)),
                ('registrar_signed', models.BooleanField(default=False)),
                ('principal_approved', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='accounts.administratorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='accounts.studentprofile')),
            ],
        ),
    ]
